In [1]:
# from google.colab import files
# files.upload()

## Import Libraries

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
import numpy as np

## Data Visualization and Cleaning

In [3]:
dataset = pd.read_csv('train.csv')

In [4]:
dataset.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [5]:
dataset.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [7]:
dataset.describe()

                Id   MSSubClass  ...       YrSold      SalePrice
count  1460.000000  1460.000000  ...  1460.000000    1460.000000
mean    730.500000    56.897260  ...  2007.815753  180921.195890
std     421.610009    42.300571  ...     1.328095   79442.502883
min       1.000000    20.000000  ...  2006.000000   34900.000000
25%     365.750000    20.000000  ...  2007.000000  129975.000000
50%     730.500000    50.000000  ...  2008.000000  163000.000000
75%    1095.250000    70.000000  ...  2009.000000  214000.000000
max    1460.000000   190.000000  ...  2010.000000  755000.000000

[8 rows x 38 columns]

In [8]:
def fillna(df): # Replacing Null Data
  list_obj = list(df.select_dtypes(include='object').columns)
  list_numric = list(df.select_dtypes(exclude='object').columns)

  for _ in list_obj:
      df[_].fillna(value=df[_].mode()[0], inplace=True) # Replace Object data type with its mode
  for _ in list_numric:
      df[_].fillna(value=df[_].mean(), inplace=True) # Replace numerical with mean

In [9]:
dataset["Alley"]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1455    NaN
1456    NaN
1457    NaN
1458    NaN
1459    NaN
Name: Alley, Length: 1460, dtype: object

In [10]:
fillna(dataset)

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          1460 non-null   object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1460 non-null   object
 26  MasVnrArea     1460 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1460 non-null   object
 31  BsmtCond       1460 non-null   object
 32  BsmtExposure   1460 non-null   object
 33  BsmtFinType1   1460 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1460 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   object
 58  GarageType     1460 non-null   object
 59  GarageYrBlt    1460 non-null   float64
 60  GarageFinish   1460 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   object
 64  GarageCond     1460 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   object
 73  Fence          1460 non-null   object
 74  MiscFeature    1460 non-null   object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [12]:
dataset["Alley"]

0       Grvl
1       Grvl
2       Grvl
3       Grvl
4       Grvl
        ...
1455    Grvl
1456    Grvl
1457    Grvl
1458    Grvl
1459    Grvl
Name: Alley, Length: 1460, dtype: object

In [13]:
def one_hot_encode(df): # One hot encode the categorical data into numerical value
  list_obj = list(df.select_dtypes(include='object').columns)
  le = LabelEncoder()

  for _ in list_obj:
    df[_] = le.fit_transform(df[_])

In [14]:
one_hot_encode(dataset)

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   int64
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   int64
 6   Alley          1460 non-null   int64
 7   LotShape       1460 non-null   int64
 8   LandContour    1460 non-null   int64
 9   Utilities      1460 non-null   int64
 10  LotConfig      1460 non-null   int64
 11  LandSlope      1460 non-null   int64
 12  Neighborhood   1460 non-null   int64
 13  Condition1     1460 non-null   int64
 14  Condition2     1460 non-null   int64
 15  BldgType       1460 non-null   int64
 16  HouseStyle     1460 non-null   int64
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   int64
 22  RoofMatl       1460 non-null   int64
 23  Exterior1st    1460 non-null   int64
 24  Exterior2nd    1460 non-null   int64
 25  MasVnrType     1460 non-null   int64
 26  MasVnrArea     1460 non-null   float64
 27  ExterQual      1460 non-null   int64
 28  ExterCond      1460 non-null   int64
 29  Foundation     1460 non-null   int64
 30  BsmtQual       1460 non-null   int64
 31  BsmtCond       1460 non-null   int64
 32  BsmtExposure   1460 non-null   int64
 33  BsmtFinType1   1460 non-null   int64
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   int64
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   int64
 40  HeatingQC      1460 non-null   int64
 41  CentralAir     1460 non-null   int64
 42  Electrical     1460 non-null   int64
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   int64
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   int64
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   int64
 58  GarageType     1460 non-null   int64
 59  GarageYrBlt    1460 non-null   float64
 60  GarageFinish   1460 non-null   int64
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   int64
 64  GarageCond     1460 non-null   int64
 65  PavedDrive     1460 non-null   int64
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   int64
 73  Fence          1460 non-null   int64
 74  MiscFeature    1460 non-null   int64
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   int64
 79  SaleCondition  1460 non-null   int64
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(78)
memory usage: 924.0 KB

In [16]:
dataset.head()

   Id  MSSubClass  MSZoning  ...  SaleType  SaleCondition  SalePrice
0   1          60         3  ...         8              4     208500
1   2          20         3  ...         8              4     181500
2   3          60         3  ...         8              4     223500
3   4          70         3  ...         8              0     140000
4   5          60         3  ...         8              4     250000

[5 rows x 81 columns]

In [17]:
dataset.tail()

        Id  MSSubClass  MSZoning  ...  SaleType  SaleCondition  SalePrice
1455  1456          60         3  ...         8              4     175000
1456  1457          20         3  ...         8              4     210000
1457  1458          70         3  ...         8              4     266500
1458  1459          20         3  ...         8              4     142125
1459  1460          20         3  ...         8              4     147500

[5 rows x 81 columns]

## Chooose Variables

In [18]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1:].values
print(X.shape)
print(y.shape)

(1460, 80)
(1460, 1)

## Data Splitting

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Choosing Principal Component

In [20]:
pca = PCA(n_components = None)
train = pca.fit_transform(X_train)
test  = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[9.85177732e-01 4.02699050e-03 2.91961489e-03 2.59470854e-03
 2.31887511e-03 1.52830099e-03 4.32541375e-04 2.61771382e-04
 2.47025652e-04 2.01692600e-04 1.24343291e-04 3.90737528e-05
 3.10425535e-05 2.87571389e-05 2.35170378e-05 1.33225676e-05
 1.10308017e-05 6.90435461e-06 6.58724404e-06 2.49664018e-06
 1.74722552e-06 1.12731439e-06 2.93047874e-07 1.56009050e-07
 6.34878496e-08 2.42696215e-08 2.04212597e-08 1.96464915e-08
 1.80474305e-08 1.72488778e-08 1.57746900e-08 1.46954599e-08
 1.39936859e-08 1.30649090e-08 9.67826990e-09 9.58819466e-09
 8.72873009e-09 7.93453297e-09 7.55613692e-09 6.41105587e-09
 6.05392935e-09 5.72058848e-09 5.56199145e-09 4.89490094e-09
 4.73138618e-09 3.90372129e-09 3.68256337e-09 3.34810297e-09
 3.23703251e-09 2.95491229e-09 2.94305562e-09 2.78369295e-09
 2.62502482e-09 2.54863371e-09 2.51449138e-09 2.28605645e-09
 2.22980696e-09 1.98268274e-09 1.64921598e-09 1.55782990e-09
 1.50177675e-09 1.33984328e-09 1.26280583e-09 1.10678919e-09
 1.06327959e-09 7.50352939e-10 6.23609913e-10 5.82512842e-10
 4.20535659e-10 3.31074331e-10 2.94604999e-10 2.12700362e-10
 1.67177966e-10 1.28809566e-10 3.14476642e-11 1.88643582e-11
 1.58238931e-11 6.50338820e-12 9.80104948e-33 9.80104948e-33]

In [21]:
sum(explained_variance)

1.0000000000000002

In [22]:
s = 0
i = 0
for _ in explained_variance:
  s += _
  print(i, s)
  i += 1

0 0.9851777323579508
1 0.9892047228591969
2 0.9921243377492354
3 0.994719046293603
4 0.9970379214018762
5 0.9985662223960047
6 0.9989987637714561
7 0.9992605351534043
8 0.9995075608052402
9 0.9997092534057337
10 0.9998335966966677
11 0.9998726704495076
12 0.9999037130030225
13 0.9999324701418784
14 0.9999559871796664
15 0.9999693097472582
16 0.999980340549006
17 0.9999872449036201
18 0.9999938321476561
19 0.9999963287878317
20 0.9999980760133548
21 0.9999992033277487
22 0.9999994963756222
23 0.9999996523846725
24 0.9999997158725221
25 0.9999997401421435
26 0.9999997605634033
27 0.9999997802098948
28 0.9999997982573253
29 0.9999998155062032
30 0.9999998312808932
31 0.999999845976353
32 0.999999859970039
33 0.9999998730349481
34 0.9999998827132179
35 0.9999998923014126
36 0.9999999010301427
37 0.9999999089646756
38 0.9999999165208125
39 0.9999999229318685
40 0.9999999289857978
41 0.9999999347063863
42 0.9999999402683777
43 0.9999999451632786
44 0.9999999498946648
45 0.9999999537983861
46 0.9999999574809495
47 0.9999999608290525
48 0.999999964066085
49 0.9999999670209974
50 0.9999999699640529
51 0.9999999727477459
52 0.9999999753727707
53 0.9999999779214045
54 0.9999999804358959
55 0.9999999827219523
56 0.9999999849517593
57 0.9999999869344421
58 0.9999999885836581
59 0.999999990141488
60 0.9999999916432647
61 0.9999999929831079
62 0.9999999942459138
63 0.999999995352703
64 0.9999999964159826
65 0.9999999971663355
66 0.9999999977899454
67 0.9999999983724582
68 0.9999999987929938
69 0.9999999991240681
70 0.9999999994186731
71 0.9999999996313735
72 0.9999999997985515
73 0.999999999927361
74 0.9999999999588086
75 0.999999999977673
76 0.9999999999934969
77 1.0000000000000002
78 1.0000000000000002
79 1.0000000000000002

In [23]:
# Choosing 49 components gives variance accuracy of 0.999999964066085
pca = PCA(n_components = 49)
X_train = pca.fit_transform(X_train)
X_test  = pca.transform(X_test)

## Create Weight and Bias Vector

In [24]:
# creating input feayure vector with first column as 1
X = np.ones(shape=(X_train.shape[0], 1+X_train.shape[1]))
X[:, 1:] = X_train

In [25]:
X.shape

(1168, 50)

## Calculating Optimized value for Bias and Weight Vector

In [26]:
# calculationg optimal weight and bias vector
inv = np.linalg.inv(np.dot(X.T, X))
theta = np.dot(inv, X.T)
theta = np.dot(theta, y_train).reshape(-1, 1)

In [27]:
print(theta.shape)

(50, 1)

## Testing of Model

In [28]:
# input feature vector for testing purpose
X_testing = np.ones(shape=(X_test.shape[0], 1+X_test.shape[1]))
X_testing[:, 1:] = X_test

## Model Prediction

In [29]:
# predicting output using linear regression
predict = np.dot(X_testing, theta).astype('int64')

for i in range(predict.shape[0]):
  print("Predicted:", predict[i], "Correct Label:", y_test[i])

Predicted: [222371] Correct Label: [200624]
Predicted: [172613] Correct Label: [133000]
Predicted: [105801] Correct Label: [110000]
Predicted: [217752] Correct Label: [192000]
Predicted: [93952] Correct Label: [88000]
Predicted: [86996] Correct Label: [85000]
Predicted: [243669] Correct Label: [282922]
Predicted: [147742] Correct Label: [141000]
Predicted: [499079] Correct Label: [745000]
Predicted: [150835] Correct Label: [148800]
Predicted: [186453] Correct Label: [208900]
Predicted: [154020] Correct Label: [136905]
Predicted: [246095] Correct Label: [225000]
Predicted: [110360] Correct Label: [123000]
Predicted: [124025] Correct Label: [119200]
Predicted: [145288] Correct Label: [145000]
Predicted: [230299] Correct Label: [190000]
Predicted: [105010] Correct Label: [123600]
Predicted: [133840] Correct Label: [149350]
Predicted: [197381] Correct Label: [155000]
Predicted: [138109] Correct Label: [166000]
Predicted: [163807] Correct Label: [144500]
Predicted: [114072] Correct Label: [110000]
Predicted: [150750] Correct Label: [174000]
Predicted: [202463] Correct Label: [185000]
Predicted: [203704] Correct Label: [168000]
Predicted: [162261] Correct Label: [177500]
Predicted: [58106] Correct Label: [84500]
Predicted: [349545] Correct Label: [320000]
Predicted: [106044] Correct Label: [118500]
Predicted: [138314] Correct Label: [110000]
Predicted: [209262] Correct Label: [213000]
Predicted: [149905] Correct Label: [156000]
Predicted: [279911] Correct Label: [250000]
Predicted: [310784] Correct Label: [372500]
Predicted: [186217] Correct Label: [175000]
Predicted: [300459] Correct Label: [277500]
Predicted: [109683] Correct Label: [112500]
Predicted: [223453] Correct Label: [263000]
Predicted: [331759] Correct Label: [325000]
Predicted: [213623] Correct Label: [243000]
Predicted: [102053] Correct Label: [130000]
Predicted: [206202] Correct Label: [164990]
Predicted: [297730] Correct Label: [280000]
Predicted: [337734] Correct Label: [403000]
Predicted: [135698] Correct Label: [119000]
Predicted: [137188] Correct Label: [125000]
Predicted: [117310] Correct Label: [128200]
Predicted: [172623] Correct Label: [172500]
Predicted: [81504] Correct Label: [84900]
Predicted: [395436] Correct Label: [412500]
Predicted: [144578] Correct Label: [156000]
Predicted: [180235] Correct Label: [167900]
Predicted: [51726] Correct Label: [100000]
Predicted: [247085] Correct Label: [275000]
Predicted: [86259] Correct Label: [123000]
Predicted: [115931] Correct Label: [132000]
Predicted: [234562] Correct Label: [239900]
Predicted: [129790] Correct Label: [139000]
Predicted: [88970] Correct Label: [115000]
Predicted: [144526] Correct Label: [137500]
Predicted: [120847] Correct Label: [135000]
Predicted: [138145] Correct Label: [134450]
Predicted: [149676] Correct Label: [180500]
Predicted: [225541] Correct Label: [193500]
Predicted: [170451] Correct Label: [156500]
Predicted: [124177] Correct Label: [132000]
Predicted: [226673] Correct Label: [224500]
Predicted: [112107] Correct Label: [139000]
Predicted: [210280] Correct Label: [225000]
Predicted: [196440] Correct Label: [188500]
Predicted: [103619] Correct Label: [118000]
Predicted: [66126] Correct Label: [82000]
Predicted: [250886] Correct Label: [392000]
Predicted: [66824] Correct Label: [112000]
Predicted: [261205] Correct Label: [248900]
Predicted: [116932] Correct Label: [134500]
Predicted: [75704] Correct Label: [79500]
Predicted: [289964] Correct Label: [320000]
Predicted: [166207] Correct Label: [158000]
Predicted: [133851] Correct Label: [140000]
Predicted: [133570] Correct Label: [136500]
Predicted: [115338] Correct Label: [107500]
Predicted: [140870] Correct Label: [145000]
Predicted: [240683] Correct Label: [200500]
Predicted: [202975] Correct Label: [185000]
Predicted: [83042] Correct Label: [105000]
Predicted: [197398] Correct Label: [202665]
Predicted: [167948] Correct Label: [186000]
Predicted: [144531] Correct Label: [136000]
Predicted: [186132] Correct Label: [200500]
Predicted: [186847] Correct Label: [190000]
Predicted: [176490] Correct Label: [187500]
Predicted: [232771] Correct Label: [200000]
Predicted: [203354] Correct Label: [172500]
Predicted: [159964] Correct Label: [157000]
Predicted: [224741] Correct Label: [213000]
Predicted: [174268] Correct Label: [185000]
Predicted: [101381] Correct Label: [124500]
Predicted: [138775] Correct Label: [162900]
Predicted: [262153] Correct Label: [260000]
Predicted: [211673] Correct Label: [198500]
Predicted: [129455] Correct Label: [120000]
Predicted: [164529] Correct Label: [159500]
Predicted: [110069] Correct Label: [105900]
Predicted: [262385] Correct Label: [260000]
Predicted: [168595] Correct Label: [143000]
Predicted: [80991] Correct Label: [106500]
Predicted: [177455] Correct Label: [178900]
Predicted: [125675] Correct Label: [127000]
Predicted: [91809] Correct Label: [90350]
Predicted: [113769] Correct Label: [118500]
Predicted: [188881] Correct Label: [190000]
Predicted: [121514] Correct Label: [119900]
Predicted: [176343] Correct Label: [183900]
Predicted: [151483] Correct Label: [155000]
Predicted: [400920] Correct Label: [386250]
Predicted: [123946] Correct Label: [133000]
Predicted: [235218] Correct Label: [193500]
Predicted: [248060] Correct Label: [270000]
Predicted: [167029] Correct Label: [141000]
Predicted: [145320] Correct Label: [146000]
Predicted: [122615] Correct Label: [128500]
Predicted: [202715] Correct Label: [176000]
Predicted: [242431] Correct Label: [214000]
Predicted: [269787] Correct Label: [222000]
Predicted: [355717] Correct Label: [415298]
Predicted: [192057] Correct Label: [187750]
Predicted: [201102] Correct Label: [199900]
Predicted: [177297] Correct Label: [180000]
Predicted: [200357] Correct Label: [206300]
Predicted: [201481] Correct Label: [194000]
Predicted: [149098] Correct Label: [142953]
Predicted: [217989] Correct Label: [182900]
Predicted: [65522] Correct Label: [116050]
Predicted: [225532] Correct Label: [213250]
Predicted: [141496] Correct Label: [139500]
Predicted: [169702] Correct Label: [179000]
Predicted: [96592] Correct Label: [107900]
Predicted: [188800] Correct Label: [175900]
Predicted: [146788] Correct Label: [158500]
Predicted: [120927] Correct Label: [145000]
Predicted: [233631] Correct Label: [217000]
Predicted: [160884] Correct Label: [150500]
Predicted: [145685] Correct Label: [108959]
Predicted: [182894] Correct Label: [165600]
Predicted: [229331] Correct Label: [201000]
Predicted: [151036] Correct Label: [145500]
Predicted: [301835] Correct Label: [319900]
Predicted: [245713] Correct Label: [215000]
Predicted: [185679] Correct Label: [180500]
Predicted: [358207] Correct Label: [367294]
Predicted: [297230] Correct Label: [239000]
Predicted: [169037] Correct Label: [145900]
Predicted: [187389] Correct Label: [161000]
Predicted: [296036] Correct Label: [250000]
Predicted: [130501] Correct Label: [89471]
Predicted: [193924] Correct Label: [230000]
Predicted: [129966] Correct Label: [147000]
Predicted: [174765] Correct Label: [163900]
Predicted: [97057] Correct Label: [97000]
Predicted: [136801] Correct Label: [142000]
Predicted: [189277] Correct Label: [197000]
Predicted: [90449] Correct Label: [129000]
Predicted: [228537] Correct Label: [232000]
Predicted: [141482] Correct Label: [115000]
Predicted: [147007] Correct Label: [175000]
Predicted: [274976] Correct Label: [265000]
Predicted: [214333] Correct Label: [207000]
Predicted: [152307] Correct Label: [181000]
Predicted: [175496] Correct Label: [176000]
Predicted: [158947] Correct Label: [171000]
Predicted: [205198] Correct Label: [196000]
Predicted: [177047] Correct Label: [176000]
Predicted: [120294] Correct Label: [113000]
Predicted: [111419] Correct Label: [139000]
Predicted: [130018] Correct Label: [135000]
Predicted: [245767] Correct Label: [240000]
Predicted: [142770] Correct Label: [112000]
Predicted: [137458] Correct Label: [134000]
Predicted: [301971] Correct Label: [316600]
Predicted: [187497] Correct Label: [170000]
Predicted: [130809] Correct Label: [116000]
Predicted: [283913] Correct Label: [306000]
Predicted: [94930] Correct Label: [82500]
Predicted: [190459] Correct Label: [175000]
Predicted: [95160] Correct Label: [106000]
Predicted: [220017] Correct Label: [194000]
Predicted: [214887] Correct Label: [194201]
Predicted: [154659] Correct Label: [155900]
Predicted: [133390] Correct Label: [138000]
Predicted: [203428] Correct Label: [177000]
Predicted: [209065] Correct Label: [214000]
Predicted: [131910] Correct Label: [148000]
Predicted: [130362] Correct Label: [127000]
Predicted: [148925] Correct Label: [142500]
Predicted: [58343] Correct Label: [80000]
Predicted: [145039] Correct Label: [145000]
Predicted: [181597] Correct Label: [171000]
Predicted: [114128] Correct Label: [122500]
Predicted: [114071] Correct Label: [139000]
Predicted: [200626] Correct Label: [189000]
Predicted: [122824] Correct Label: [120500]
Predicted: [113409] Correct Label: [124000]
Predicted: [115877] Correct Label: [160000]
Predicted: [217193] Correct Label: [200000]
Predicted: [170385] Correct Label: [160000]
Predicted: [330899] Correct Label: [313000]
Predicted: [250477] Correct Label: [275000]
Predicted: [33624] Correct Label: [67000]
Predicted: [149767] Correct Label: [159000]
Predicted: [258492] Correct Label: [251000]
Predicted: [56675] Correct Label: [92900]
Predicted: [95389] Correct Label: [109500]
Predicted: [354238] Correct Label: [385000]
Predicted: [205865] Correct Label: [129000]
Predicted: [191770] Correct Label: [82500]
Predicted: [287759] Correct Label: [301000]
Predicted: [236544] Correct Label: [249700]
Predicted: [72361] Correct Label: [81000]
Predicted: [199066] Correct Label: [187500]
Predicted: [139340] Correct Label: [110000]
Predicted: [162892] Correct Label: [117000]
Predicted: [124956] Correct Label: [128500]
Predicted: [197633] Correct Label: [213490]
Predicted: [262158] Correct Label: [284000]
Predicted: [231210] Correct Label: [230500]
Predicted: [231687] Correct Label: [190000]
Predicted: [135015] Correct Label: [135000]
Predicted: [159720] Correct Label: [152000]
Predicted: [66320] Correct Label: [87500]
Predicted: [176867] Correct Label: [155000]
Predicted: [84455] Correct Label: [115000]
Predicted: [142548] Correct Label: [144000]
Predicted: [245178] Correct Label: [248000]
Predicted: [131203] Correct Label: [132500]
Predicted: [126941] Correct Label: [136000]
Predicted: [124184] Correct Label: [117000]
Predicted: [82292] Correct Label: [82000]
Predicted: [178273] Correct Label: [157500]
Predicted: [123206] Correct Label: [110000]
Predicted: [170678] Correct Label: [181000]
Predicted: [212111] Correct Label: [192500]
Predicted: [218911] Correct Label: [223500]
Predicted: [193748] Correct Label: [181500]
Predicted: [162438] Correct Label: [170000]
Predicted: [211744] Correct Label: [187500]
Predicted: [197533] Correct Label: [185900]
Predicted: [127138] Correct Label: [160000]
Predicted: [217305] Correct Label: [192000]
Predicted: [188245] Correct Label: [181900]
Predicted: [250254] Correct Label: [266000]
Predicted: [94437] Correct Label: [99900]
Predicted: [396067] Correct Label: [438780]
Predicted: [230882] Correct Label: [229456]
Predicted: [232806] Correct Label: [216837]
Predicted: [116568] Correct Label: [110500]
Predicted: [220079] Correct Label: [175900]
Predicted: [441782] Correct Label: [538000]
Predicted: [789806] Correct Label: [160000]
Predicted: [202260] Correct Label: [172500]
Predicted: [107067] Correct Label: [108000]
Predicted: [149321] Correct Label: [131500]
Predicted: [57031] Correct Label: [106250]
Predicted: [421147] Correct Label: [385000]
Predicted: [334969] Correct Label: [370878]
Predicted: [341359] Correct Label: [345000]
Predicted: [83070] Correct Label: [68500]
Predicted: [236493] Correct Label: [250000]
Predicted: [248802] Correct Label: [245350]
Predicted: [140649] Correct Label: [125000]
Predicted: [226752] Correct Label: [234000]
Predicted: [127688] Correct Label: [145000]
Predicted: [168292] Correct Label: [181000]
Predicted: [123620] Correct Label: [104000]
Predicted: [240326] Correct Label: [233000]
Predicted: [234871] Correct Label: [164000]
Predicted: [171687] Correct Label: [219500]
Predicted: [217796] Correct Label: [195000]
Predicted: [109137] Correct Label: [108000]
Predicted: [116590] Correct Label: [149900]
Predicted: [349600] Correct Label: [315000]
Predicted: [163485] Correct Label: [177500]
Predicted: [139299] Correct Label: [140000]
Predicted: [204964] Correct Label: [193879]
Predicted: [167056] Correct Label: [137900]
Predicted: [124050] Correct Label: [118000]
Predicted: [270629] Correct Label: [324000]
Predicted: [433127] Correct Label: [555000]
Predicted: [214794] Correct Label: [136000]
Predicted: [95450] Correct Label: [82500]
Predicted: [109290] Correct Label: [101000]

## Error Computation

In [30]:
error = y_test - predict
sq_err = np.square(error)
RMSE = np.sqrt(np.sum(sq_err))
print("RMSE:", RMSE)

RMSE: 815891.9986113358